name: chatgpdb-dev
channels:
  - conda-forge

dependencies:
  - uvicorn
  - gunicorn
  - django
  - websockets

  - jupyter
  - transformers
  - pytorch
  - spacy
  - ftfy
  - accelerate
  - black
  - daphne

  - parmed

  - pip
  - pip:
    - channels
    - pytorch-transformers
